---
- name: Install Caddy Server
  hosts: all
  tasks:
    - name: Create a Docker network
      docker_network:
        name: caddy_network
        driver: bridge

    - name: Pull Caddy image
      docker_image:
        name: caddy:latest
        tag: latest
        source: pull
        state: present

    - name: Create directory and add multiline content to file
      ansible.builtin.shell: |
        mkdir -p /tmp/caddy/
        cat << EOF > /tmp/caddy/Caddyfile
        *.deploypocket.com {
          reverse_proxy {labels.2}:8090
        }
        EOF

    - name: Run Caddy in a Docker container
      docker_container:
        name: caddy_server
        image: caddy:latest
        state: started
        restart_policy: always
        volumes:
          - "/tmp/caddy/Caddyfile:/etc/caddy/Caddyfile:ro"
          - "/tmp/caddy/site:/srv"
          - "/tmp/caddy/data:/data"
          - "/tmp/caddy/config:/config"
        ports:
          - "80:80"
          - "443:443"
          - "443:443/udp"
        networks:
          - name: caddy_network
