---
- name: Build and run PocketBase Docker container
  hosts: all
  connection: local
  tasks:
    - name: Ensure App Directories Exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "/deploypocket/pocketbase"
        - "/deploypocket/apps/{{ instance_code }}/pb/migrations"
        - "/deploypocket/apps/{{ instance_code }}/pb/pb_data"
        - "/deploypocket/apps/{{ instance_code }}/pb/pb_hooks"
        - "/deploypocket/apps/{{ instance_code }}/pb/storage"

    - name: Create hooks file
      file:
        path: "/deploypocket/apps/{{ instance_code }}/pb/pb_hooks/main.pb.js"
        state: touch
        
    - name: Write Dockerfile for PocketBase
      copy:
        dest: "/deploypocket/pocketbase/Dockerfile"
        content: |
          FROM alpine:latest
          ARG PB_VERSION=0.22.19
          
          RUN apk add --no-cache \
              unzip \
              ca-certificates
          # download and unzip PocketBase
          ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pb.zip
          RUN unzip /tmp/pb.zip -d /pb/
          # start PocketBase
          CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8090"]
          
    - name: Build PocketBase Docker image
      docker_image:
        name: "pocketbase-003-{{ pb_version }}"
        source: build
        build:
          path: /deploypocket/pocketbase/
          dockerfile: /deploypocket/pocketbase/Dockerfile
          args:
            PB_VERSION: "{{ pb_version }}"
        state: present
        force_tag: true


    - name: Run PocketBase Docker container
      docker_container:
        name: "{{ instance_code }}"
        image: "pocketbase-003-{{ pb_version }}:latest"
        state: started
        restart_policy: always
        networks:
          - name: caddy_network
        volumes:
          - "/deploypocket/apps/{{ instance_code }}/pb/migrations:/pb/migrations"
          - "/deploypocket/apps/{{ instance_code }}/pb/pb_data:/pb/pb_data"
          - "/deploypocket/apps/{{ instance_code }}/pb/pb_hooks:/pb/pb_hooks"
          - "/deploypocket/apps/{{ instance_code }}/pb/storage:/pb/storage"
        labels:
          "sablier.enable": "true"

    - name: Run Pocketbase Migrations
      community.docker.docker_container_exec:
        container: "{{ instance_code }}"
        argv:
          - /pb/pocketbase
          - "migrate"
          - "up"

    - name: Create Admin Account
      community.docker.docker_container_exec:
        container: "{{ instance_code }}"
        argv:
          - /pb/pocketbase
          - "admin"
          - "create"
          - "{{ admin_email }}"
          - "{{ admin_password }}"
