---
- name: Build and run PocketBase Docker container
  hosts: all
  tasks:
    - name: Write Dockerfile for PocketBase
      ansible.builtin.shell: |
        mkdir -p /tmp/pocketbase/
        cat << EOF > /tmp/pocketbase/Dockerfile
        FROM alpine:latest

        ARG PB_VERSION=0.22.19

        # Set environment variables
        ENV ADMIN_EMAIL=
        ENV ADMIN_PASSWORD=

        RUN apk add --no-cache \
            unzip \
            ca-certificates

        # download and unzip PocketBase
        ADD https://github.com/pocketbase/pocketbase/releases/download/v0.22.19/pocketbase_0.22.19_linux_arm64.zip /tmp/pb.zip
        RUN unzip /tmp/pb.zip -d /pb/

        # uncomment to copy the local pb_migrations dir into the image
        # COPY ./pb_migrations /pb/pb_migrations

        # uncomment to copy the local pb_hooks dir into the image
        # COPY ./pb_hooks /pb/pb_hooks

        # start PocketBase
        CMD ["sh", "-c", "/pb/pocketbase migrate up && /pb/pocketbase admin create $ADMIN_EMAIL $ADMIN_PASSWORD && /pb/pocketbase serve --http=0.0.0.0:8080"]
        EOF

      
    - name: Build PocketBase Docker image
      docker_image:
        name: "pocketbase-{{ pb_version }}"
        source: build
        build:
          path: /tmp/pocketbase/
          dockerfile: /tmp/pocketbase/Dockerfile
          args:
            PB_VERSION: "{{ pb_version }}"
        state: present
        force_tag: true

    - name: Run PocketBase Docker container
      docker_container:
        name: "{{ instance_code }}"
        image: "pocketbase-{{ pb_version }}:latest"
        state: started
        restart_policy: always
        env:
          ADMIN_EMAIL: "{{ admin_email }}"
          ADMIN_PASSWORD: "{{ admin_password }}"
        networks:
          - name: caddy_network
