---
- name: Build and run PocketBase Docker container
  hosts: all
  connection: local
  tasks:
    - name: Write Dockerfile for PocketBase
      copy:
        dest: "/tmp/pocketbase/Dockerfile"
        content: |
          FROM alpine:latest
          
          ARG PB_VERSION=0.22.19
          
          RUN apk add --no-cache unzip ca-certificates
          
          ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pb.zip
          RUN unzip /tmp/pb.zip -d /pb/
          
          CMD ["pb/pocketbase", "serve", "--http=0.0.0.0:8090"]

    - name: Ensure the app directory exists
      file:
        path: "{{ pocketbase_apps_dir }}/{{ instance_code }}/pb/{{ item }}"
        state: directory
      with_items:
        - migrations
        - pb_data
        - pb_hooks
      
    - name: Create hooks file
      file:
        path: "{{ pocketbase_apps_dir }}/{{ instance_code }}/pb/pb_hooks/main.pb.js"
        state: touch
   
    - name: Build PocketBase Docker image
      docker_image:
        name: "pocketbase-{{ pb_version }}"
        source: build
        build:
          path: /tmp/pocketbase/
          dockerfile: /tmp/pocketbase/Dockerfile
          args:
            PB_VERSION: "{{ pb_version }}"
        state: present
        force_tag: true


    - name: Run PocketBase Docker container
      docker_container:
        name: "{{ instance_code }}"
        image: "pocketbase-{{ pb_version }}:latest"
        state: started
        restart_policy: always
        networks:
          - name: caddy_network
        volumes:
          - "{{ pocketbase_apps_dir }}/{{ instance_code }}/pb/migrations:/pb/migrations"
          - "{{ pocketbase_apps_dir }}/{{ instance_code }}/pb/pb_data:/pb/pb_data"
          - "{{ pocketbase_apps_dir }}/{{ instance_code }}/pb/pb_hooks:/pb/pb_hooks"

    - name: Run migrations
      community.docker.docker_container_exec:
        container: "{{ instance_code }}"
        argv:
          - /pb/pocketbase
          - "migrate"
          - "up"

    - name: Create Admin Account
      community.docker.docker_container_exec:
        container: "{{ instance_code }}"
        argv:
          - /pb/pocketbase
          - "admin"
          - "create"
          - "{{ admin_email }}"
          - "{{ admin_password }}"
