---
- name: Build and run PocketBase Docker container
  hosts: all
  connection: local
  tasks:
    - name: Write Dockerfile for PocketBase
      copy:
        dest: "/tmp/pocketbase/Dockerfile"
        content: |
          FROM alpine:latest

          ARG PB_VERSION=0.22.19

          ENV ADMIN_EMAIL=
          ENV ADMIN_PASS=

          RUN apk add --no-cache \
              unzip \
              ca-certificates

          # download and unzip PocketBase
          ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pb.zip
          RUN unzip /tmp/pb.zip -d /pb/

          # start PocketBase
          CMD ["sh", "-c", "/pb/pocketbase migrate up && /pb/pocketbase admin create $ADMIN_EMAIL $ADMIN_PASS && /pb/pocketbase serve --http=0.0.0.0:8090"]

      
    - name: Build PocketBase Docker image
      docker_image:
        name: "pocketbase-1-{{ pb_version }}"
        source: build
        build:
          path: /tmp/pocketbase/
          dockerfile: /tmp/pocketbase/Dockerfile
          args:
            PB_VERSION: "{{ pb_version }}"
        state: present
        force_tag: true

    - name: Run PocketBase Docker container
      docker_container:
        name: "{{ instance_code }}"
        image: "pocketbase-1-{{ pb_version }}:latest"
        state: started
        restart_policy: always
        env:
          ADMIN_EMAIL: "{{ admin_email }}"
          ADMIN_PASS: "{{ admin_password }}"
        networks:
          - name: caddy_network
