---
- name: Build and run PocketBase Docker container
  hosts: all
  tasks:
    - name: Write Dockerfile for PocketBase
      copy:
        dest: "/tmp/pocketbase/Dockerfile"
        content: |
          FROM alpine:latest

          ARG PB_VERSION=0.22.19
          
          RUN apk add --no-cache \
              unzip \
              ca-certificates

          # download and unzip PocketBase
          ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_arm64.zip /tmp/pb.zip
          RUN unzip /tmp/pb.zip -d /pb/

          # the default command
          ENV RUN_CMD="/pb/pocketbase serve --http=0.0.0.0:8090"

          # start PocketBase
          CMD sh -c "$RUN_CMD"

    - name: Ensure the app directory exists
      file:
        path: "{{ pocketbase_apps_dir }}/{{ instance_code }}/pb"
        state: directory
      
    - name: Build PocketBase Docker image
      docker_image:
        name: "pocketbase-1-{{ pb_version }}"
        source: build
        build:
          path: /tmp/pocketbase/
          dockerfile: /tmp/pocketbase/Dockerfile
          args:
            PB_VERSION: "{{ pb_version }}"
        state: present
        force_tag: true

    - name: Run PocketBase Docker container
      docker_container:
        name: "{{ instance_code }}"
        image: "pocketbase-1-{{ pb_version }}:latest"
        state: started
        restart_policy: always
        env:
          RUN_CMD: "/pb/pocketbase migrate up && /pb/pocketbase admin create {{ admin_email }} {{ admin_password }} && /pb/pocketbase serve --http=0.0.0.0:8090"
        networks:
          - name: caddy_network
        volumes:
          - "{{ pocketbase_apps_dir }}/{{ instance_code }}/pb/migrations:/pb/migrations"
          - "{{ pocketbase_apps_dir }}/{{ instance_code }}/pb/pb_data:/pb/pb_data"
