---
- name: Delete PocketBase Docker container
  hosts: all
  connection: local
  tasks:
    - name: Delete PocketBase Docker container
      docker_container:
        name: "{{ instance_code }}"
        state: absent
        keep_volumes: false

    - name: Remove App Directory from Host
      file:
        path: "/deploypocket/apps/{{ instance_code }}"
        state: absent

    - name: Reload caddy configuration
      include_tasks: "reload_caddy_configuration.yml"
