---
- name: Delete PocketBase Docker container
  hosts: all
  connection: local
  become: yes
  tasks:
    - name: Delete PocketBase Docker container
      docker_container:
        name: "{{ instance_code }}"
        state: absent
        
    - name : Delete Related Directories 
      file:
        path: "{{ pocketbase_apps_dir }}/{{ instance_code }}"
        state: absent
