---
- name: Delete PocketBase Docker container
  hosts: all
  connection: local
  become: yes
  tasks:
    - name: Delete PocketBase Docker container
      docker_container:
        name: "{{ instance_code }}"
        state: absent
        keep_volumes: false

    - name: Remove associated volumes
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ pocketbase_apps_dir }}/{{ instance_code }}/pb/migrations"
        - "{{ pocketbase_apps_dir }}/{{ instance_code }}/pb/pb_data"
