---
- name: Delete PocketBase Docker container
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Delete PocketBase Docker container
      docker_container:
        name: "{{ instance_code }}"
        state: absent
        keep_volumes: false

    - name: Remove App Directory from Host
      file:
        path: "/pocketbase_apps/{{ instance_code }}"
        state: absent
