---
- name: Delete PocketBase Docker container
  hosts: all
  connection: local
  tasks:
    - name: Delete PocketBase Docker container
      docker_container:
        name: "{{ instance_code }}"
        state: absent

    - name: Remove App Directory
      file:
        path: "{{ pocketbase_apps_dir }}/{{ instance_code }}"
        state: absent
