---
- name: Update main.pb.js in the volume directory
  hosts: all
  tasks:
    - name: Saving the hook code
      ansible.builtin.copy:
        dest: "/deploypocket/apps/{{ instance_code }}/pb/pb_hooks/main.pb.js"
        content: "{{ content }}"