---
- name: Pull Caddy image
  docker_image:
    name: caddy:latest
    tag: latest
    source: pull
    state: present
    
- name: Create Caddyfile
  ansible.builtin.copy:
    content: |
      {
          servers {
              metrics
          }
          admin :2019
      }
      
      http://*.deploypocket.com {
        reverse_proxy {labels.2}:8090
      }

    dest: /deploypocket/caddy/Caddyfile
    mode: '0644'

- name: Deploy Caddy Proxy Service
  docker_container:
    name: caddy_server
    image: caddy
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
      - "443:443/udp"
    networks:
      - name: caddy_network
    volumes:
      - /deploypocket/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    state: started
    restart_policy: always
