---
- name: Pull Caddy image
  - name: Build Docker image
    community.docker.docker_image:
      build:
        path: "https://github.com/acouvreur/sablier.git#v1.4.0-beta.3:plugins/caddy"
        args:
          CADDY_VERSION: "2.6.4"
      name: "caddy"
      tag: "2.6.4-with-sablier"
    
- name: Create Caddyfile
  ansible.builtin.copy:
    content: |
      {
          servers {
              metrics
          }
          admin :2019
      }
      
      import /deploypocket/apps/*/caddy+sablier.conf
    dest: /deploypocket/caddy/Caddyfile
    mode: '0644'

- name: Deploy Caddy Proxy Service
  docker_container:
    name: caddy_server
    image: caddy:2.6.4-with-sablier
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
      - "443:443/udp"
    networks:
      - name: caddy_network
    volumes:
      - /deploypocket/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /deploypocket/apps:/deploypocket/apps:ro
    state: started
    restart_policy: always
