---
- name: Write Dockerfile for Caddy
  copy:
    dest: "/deploypocket/caddy/Dockerfile"
    content: |
      ARG CADDY_VERSION=2.6.4
      FROM caddy:${CADDY_VERSION}-builder AS builder

      ADD https://github.com/acouvreur/sablier.git#v1.4.0-beta.3 /sablier

      RUN xcaddy build \
          --with github.com/acouvreur/sablier/plugins/caddy=/sablier/plugins/caddy

      FROM caddy:${CADDY_VERSION}

      COPY --from=builder /usr/bin/caddy /usr/bin/caddy

- name: Build PocketBase Docker image
  docker_image:
    name: caddy
    tag: 2.6.4-with-sablier
    source: build
    build:
      path: /deploypocket/caddy/
      dockerfile: /deploypocket/caddy/Dockerfile
      args:
        CADDY_VERSION: 2.6.4
    state: present
    force_tag: true
    
- name: Create Caddyfile
  ansible.builtin.copy:
    content: |
      {
          servers {
              metrics
          }
          admin :2019
      }
      
      import /deploypocket/apps/*/caddy+sablier.conf
    dest: /deploypocket/caddy/Caddyfile
    mode: '0644'

- name: Deploy Caddy Proxy Service
  docker_container:
    name: caddy_server
    image: caddy:2.6.4-with-sablier
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
      - "443:443/udp"
    networks:
      - name: caddy_network
    volumes:
      - /deploypocket/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /deploypocket/apps:/deploypocket/apps:ro
    state: started
    restart_policy: always
