---
- name: Start PocketBase Docker container
  hosts: all
  connection: local
  tasks:
    - name: Start PocketBase Docker container
      docker_container:
        name: "{{ instance_code }}"
        state: started
        networks:
          - name: caddy_network
        volumes:
          - "/deploypocket/apps/{{ instance_code }}/pb/migrations:/pb/migrations"
          - "/deploypocket/apps/{{ instance_code }}/pb/pb_data:/pb/pb_data"
          - "/deploypocket/apps/{{ instance_code }}/pb/pb_hooks:/pb/pb_hooks"
