---
- name: Start PocketBase Docker container
  hosts: all
  connection: local
  tasks:
    - name: Start PocketBase Docker container
      docker_container:
        name: "{{ instance_code }}"
        command: ["/pb/pocketbase", "serve", "--http:0.0.0.0:8090"]
        state: started
        networks:
          - name: caddy_network
        volumes:
          - "{{ pocketbase_apps_dir }}/{{ instance_code }}/pb/migrations:/pb/migrations"
          - "{{ pocketbase_apps_dir }}/{{ instance_code }}/pb/pb_data:/pb/pb_data"
