---
- name: Stop PocketBase Docker container
  hosts: all
  connection: local
  tasks:
    - name: Stop PocketBase Docker container
      docker_container:
        name: "{{ instance_code }}"
        state: stopped
